Planitarium Web App/PlanetariumService/PlanetariumService/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using PlanetariumModels;
using PlanetariumServices;
using Microsoft.AspNetCore.Authorization;
using PlanetariumService.Models;

namespace PlanetariumService.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUsersService userService;

        public AuthController(IUsersService userService)
        {
            this.userService = userService;
        }


        [Route("Signin")]
        public IActionResult SignIn()
        {
            if (HttpContext.Session.GetInt32("userId") != null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [Route("Signup")]
        public IActionResult SignUp()
        {
            if (HttpContext.Session.GetInt32("userId") != null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // [Route("Signin/Login")]
        [Route("Signin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(LoginUI model) // LoginViewModel model
        {
            if (ModelState.IsValid)
            {
                // var userdetails = await _context.Userdetails
                // .SingleOrDefaultAsync(m => m.Email == model.Email && m.Password == model.Password);
                /*Users user = null; 
                try {
                    user = userService.GetByUsername(model.Login);
                } catch (AggregateException e) {
                    //ModelState.AddModelError("Login", "Invalid Username.");
                    ViewBag.LoginError = "Invalid Username.";
                    return RedirectToAction(nameof(SignIn));
                }*/
                var user = userService.GetByUsername(model.Login);
                if (user == null)
                {
                    user = userService.GetByEmail(model.Login);
                    if (user == null)
                    {
                        TempData["LoginError"] = "Invalid Username or Email.";
                        return RedirectToAction(nameof(SignIn));
                    }
                    // ModelState.AddModelError("Login", "Invalid Username.");
                }
                if (user.UserPassword != model.Password)
                {
                    //ModelState.AddModelError("Password", "Invalid Sign in attempt.");
                    TempData["PasswordError"] = "Invalid Sign in attempt. (Wrong Password)";
                    return RedirectToAction(nameof(SignIn));
                }
                //HttpContext.Session.SetString("userName", user.Username);
                TempData["Alert"] = "Signed in successfully!";
                HttpContext.Session.SetInt32("userId", user.Id);

                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction(nameof(SignIn));//View("Index");
        }
        /*{
            // TODO: Insert login and password retrival from database
            // User user;
            var user = new { Username = "Me", Password = "1234", Role = "Admin" };
            if (user.Username == login && user.Password == password)
            {
                var identity = new GenericIdentity(login);
                HttpContext.User = new GenericPrincipal(identity, new[] { user.Role });
            }
            return View();
        }*/

        // [Route("Signup/Register")]
        [Route("Signup")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(RegisterUI model) {//(RegistrationViewModel model)
            if (ModelState.IsValid)
            {
                bool error = false;
                if (userService.GetByUsername(model.Username) != null)
                {
                    TempData["UsernameError"] = "Username already used.";
                    error = true;
                }
                if (userService.GetByEmail(model.Email) != null)
                {
                    TempData["EmailError"] = "Email already used.";
                    error = true;
                }

                if (error)
                {
                    return RedirectToAction(nameof(SignUp));
                }

                Users user = new Users
                {
                    Username = model.Username,
                    /*Name = model.Name,
                    Lastame = model.Lastname,*/
                    Email = model.Email,
                    UserPassword = model.UserPassword

                };
                var res = userService.Add(user);
                // HttpContext.Session = user.Username;
                //HttpContext.Session.SetString("userName", user.Username);
                TempData["Alert"] = "Registration complete. Signed in successfully!";
                HttpContext.Session.SetInt32("userId", user.Id);
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction(nameof(SignUp));//View();
        }

        //[Authorize]
        public ActionResult Logout()
        {
            if (HttpContext.Session.GetInt32("userId") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            HttpContext.Session.Clear();
            return RedirectToAction(nameof(SignIn));
            // return RedirectToPage()
        }
    }
}

Planitarium Web App/PlanetariumService/PlanetariumService/Controllers/PostersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PlanetariumModels;
using PlanetariumServices;
using PlanetariumService.Models;

namespace PlanetariumService.Controllers
{
    public class PostersController : Controller
    {
        private readonly IPosterService posterService;
        private readonly IHallService hallService;
        private readonly IPerformanceService performanceService;
        private readonly ITicketService ticketService;
        private readonly IMapper mapper;
        public PostersController(IPosterService posterService, IHallService hallService,
            ITicketService ticketService, IPerformanceService performanceService, IMapper mapper)
        {
            this.posterService = posterService;
            this.hallService = hallService;
            this.performanceService = performanceService;
            this.ticketService = ticketService;
            this.mapper = mapper;
        }
        public ViewResult Posters(DateTime? dateFrom = null, DateTime? dateTo = null)
        {


            if (dateFrom == null || dateTo == null)
            {
                dateFrom = DateTime.Now;
                dateTo = DateTime.Now.AddDays(7);
            }
            List<Poster> posters = posterService.Posters((DateTime)dateFrom, (DateTime)dateTo);
            List<PosterUI> result = mapper.Map<List<PosterUI>>(posters);

            return View(result);
        }
        public IActionResult AddPosters()
        {
            return View(posterService.GetAll());
        }
        public IActionResult Create()
        {
            ViewData["HallId"] = new SelectList(hallService.GetAll(), "Id", "HallName");
            ViewData["PerformanceId"] = new SelectList(performanceService.GetAll(), "Id", "Title");
            return View();
        }

        public IPosterService GetPosterService()
        {
            return posterService;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAsync([Bind("Id,DateOfEvent,Price,PerformanceId,HallId")] Poster poster, DateTime? dateFrom = null, DateTime? dateTo = null)
        {
            if (ModelState.IsValid)
            {
                var pos = posterService.Add(poster);
                await CreateTickets(poster);
                return RedirectToAction(nameof(AddPosters));
            }
            ViewData["HallId"] = new SelectList(hallService.GetAll(), "Id", "Id", poster.HallId);
            ViewData["PerformanceId"] = new SelectList(performanceService.GetAll(), "Id", "Id", poster.PerformanceId);
            return View(poster);
        }

        public async Task CreateTickets(Poster poster)
        {
            for (int i = 1; i <= (int)hallService.GetById(poster.HallId).Capacity; i++)
            {
                Ticket ticket = new() { Place = (byte)i, TicketStatus = "available", TierId = 1, PosterId = poster.Id };
                await ticketService.Add(ticket);
            }
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var poster = posterService.GetById((int)id);
            if (poster == null)
            {
                return NotFound();
            }
            ViewData["HallId"] = new SelectList(hallService.GetAll(), "Id", "HallName", poster.HallId);
            ViewData["PerformanceId"] = new SelectList(performanceService.GetAll(), "Id", "Title", poster.PerformanceId);
            return View(poster);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,DateOfEvent,Price,PerformanceId,HallId")] Poster poster)
        {
            if (id != poster.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    posterService.Update(poster);
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(AddPosters));
            }
            ViewData["HallId"] = new SelectList(hallService.GetAll(), "Id", "Id", poster.HallId);
            ViewData["PerformanceId"] = new SelectList(performanceService.GetAll(), "Id", "Id", poster.PerformanceId);
            return View(poster);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            return View(posterService.GetById((int)id));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var poster = posterService.GetById(id);
            posterService.Delete(poster);
            return RedirectToAction(nameof(AddPosters));
        }

    }
}

Planitarium Web App/PlanetariumService/PlanetariumService/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PlanetariumService</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" type="text/css" href="~/css/all.css" asp-append-version="true" />
    @if (@ViewData["CSS"] != null)
    {
    <link rel="stylesheet" type="text/css" href="@ViewData["CSS"]" asp-append-version="true" />
    }
    @if (@ViewData["Head"] != null) {
    @Html.Raw(@ViewData["Head"])
    }
    <!--  <link rel="preconnect" href="https://fonts.googleapis.com">-->
    <!--  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>-->
    <!--  <link href="https://fonts.googleapis.com/css2?family=Raleway&family=Ubuntu&display=swap" rel="stylesheet">-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="~/js/change.js"></script>
</head>
<body>
    <nav>
        <div class="links">
            <a asp-area="" asp-controller="Home" asp-action="Index" style="all: revert;">
                <!--    <img src="img/icon.svg">-->
                <svg xmlns="http://www.w3.org/2000/svg" width="100.000000pt" height="100.000000pt"
                     viewBox="0 0 1024.000000 1024.000000">

                    <g stroke="none">
                        <circle cx="512" cy="512" r="120" />
                        <path d="M70 985 c0 -8 7 -15 15 -15 8 0 15 7 15 15 0 8 -7 15 -15 15 -8 0 -15 -7 -15 -15z" />
                        <path d="M910 985 c0 -8 -7 -15 -15 -15 -8 0 -15 -9 -15 -20 0 -11 7 -20 15 -20 8 0 15 -7 15 -15 0 -8 9 -15 20 -15
          11 0 20 7 20 15 0 8 7 15 15 15 8 0 15 9 15 20 0 11 -7 20 -15 20 -8 0 -15 7 -15 15 0 8 -9 15 -20 15 -11 0 -20
          -7 -20 -15z m38 -38 c2 -12 -3 -17 -17 -17 -15 0 -21 6 -21 21 0 25 33 22 38 -4z" />
                        <path d="M20 930 c0 -11 7 -20 15 -20 8 0 15 9 15 20 0 11 -7 20 -15 20 -8 0 -15 -9 -15 -20z" />
                        <path d="M70 140 c0 -11 7 -20 15 -20 8 0 15 9 15 20 0 11 -7 20 -15 20 -8 0 -15 -9 -15 -20z" />
                        <path d="M910 140 c0 -11 -7 -20 -15 -20 -8 0 -15 -7 -15 -15 0 -8 7 -15 15 -15 8 0 15 -9 15 -20 0 -13 7 -20 20
          -20 13 0 20 7 20 20 0 11 7 20 15 20 8 0 15 7 15 15 0 8 -7 15 -15 15 -8 0 -15 9 -15 20 0 13 -7 20 -20 20 -13 0
          -20 -7 -20 -20z m40 -35 c0 -8 -9 -15 -20 -15 -11 0 -20 7 -20 15 0 8 9 15 20 15 11 0 20 -7 20 -15z" />
                        <path d="M20 85 c0 -8 7 -15 15 -15 8 0 15 7 15 15 0 8 -7 15 -15 15 -8 0 -15 -7 -15 -15z" />
                        <path d="M120 85 c0 -8 9 -15 20 -15 11 0 20 7 20 15 0 8 -9 15 -20 15 -11 0 -20 -7 -20 -15z" />
                        <path d="M70 35 c0 -8 7 -15 15 -15 8 0 15 7 15 15 0 8 -7 15 -15 15 -8 0 -15 -7 -15 -15z" />
                        <path style="transform-origin: 450px 510.5px" class="rotate-slow" d="M454 959 c-67 -9 -119 -26 -171 -55 -31 -18
          -47 -22 -65 -15 -52 19 -114 -40 -90 -86 8 -15 3 -34 -23 -85 -18 -37 -38 -98 -45 -137 -38 -226 112 -456 334
          -512 25 -6 46 -15 46 -20 0 -17 44 -49 68 -49 14 0 36 13 51 29 15 16 47 35 72 41 119 32 237 131 289 242 65 140
          55 309 -27 441 -16 25 -21 45 -17 61 8 33 -28 70 -62 62 -16 -4 -38 3 -71 23 -81 49 -194 73 -289 60z m161 -45
          c83 -21 142 -58 159 -98 9 -22 24 -37 44 -44 37 -13 75 -74 96 -157 51 -194 -38 -390 -216 -480 -81 -40 -109 -43
          -145 -15 -34 27 -65 25 -94 -4 l-25 -24 -59 20 c-111 37 -195 114 -249 227 -29 61 -31 74 -31 171 0 101 2 109 35
          175 30 61 39 70 64 72 38 3 66 30 66 64 0 35 28 55 119 86 78 27 154 29 236 7z m-394 -70 c17 -21 0 -49 -32 -49
          -18 0 -25 6 -27 24 -6 38 34 55 59 25z m619 -19 c0 -8 -7 -15 -15 -15 -8 0 -15 7 -15 15 0 8 7 15 15 15 8 0 15 -7
          15 -15z m-305 -755 c0 -20 -6 -26 -26 -28 -17 -2 -29 3 -32 12 -11 28 4 47 32 44 20 -2 26 -8 26 -28z" />
                        <!--          <animateMotion dur="1s" repeatCount="indefinite" type="rotate" from="0" to="360"></animateMotion>-->
                        <!--        </path>-->
                        <path style="transform-origin: 343px 349px" class="rotate-average" d="M409 845 c-107 -34 -202 -128 -234 -232 -23
          -74 -17 -180 15 -248 13 -27 23 -64 21 -82 -3 -42 30 -77 67 -70 17 4 46 -4 80 -20 71 -35 178 -42 255 -18 104 32
          203 133 230 232 6 24 14 43 18 43 4 0 15 7 23 16 24 23 20 69 -8 91 -13 11 -26 32 -30 49 -19 86 -105 183 -200
          225 -62 27 -175 34 -237 14z m226 -49 c87 -40 144 -103 176 -193 9 -27 8 -34 -10 -52 -27 -27 -27 -51 0 -85 l20
          -26 -24 -54 c-47 -103 -125 -164 -239 -188 -94 -19 -228 24 -228 74 0 34 -14 49 -51 57 -28 5 -38 15 -59 56 -20
          40 -25 64 -24 125 1 89 23 146 80 209 64 72 129 99 234 100 59 1 86 -4 125 -23z m231 -277 c8 -14 -21 -43 -35 -35
          -19 12 -13 46 8 46 11 0 23 -5 27 -11z m-572 -235 c8 -21 -1 -34 -25 -34 -12 0 -19 7 -19 18 0 34 33 45 44 16z" />
                        <!--          <animateMotion dur="1s" repeatCount="indefinite" rotate="auto"></animateMotion>-->
                        <!--        </path>-->
                        <path style="transform-origin: 276px 242px" class="rotate-fast" d="M470 770 c-11 -11 -35 -26 -53 -34 -53 -22
          -108 -77 -133 -132 -12 -28 -30 -54 -38 -57 -22 -9 -21 -63 2 -79 10 -7 24 -29 32 -48 20 -48 75 -107 124 -132 87
          -45 215 -20 281 54 49 53 65 95 65 166 0 102 -50 182 -138 220 -26 11 -56 30 -66 41 -24 26 -50 27 -76 1z m51 -35
          c-1 -15 -24 -12 -29 3 -3 9 2 13 12 10 10 -1 17 -7 17 -13z m-36 -41 c23 -15 27 -15 51 1 35 23 67 13 117 -38 82
          -82 88 -199 14 -284 -85 -96 -229 -96 -314 1 -37 41 -51 82 -34 99 14 14 14 60 0 74 -25 25 23 106 86 144 37 23
          49 23 80 3z m-193 -196 c-9 -9 -15 -9 -24 0 -10 10 -10 15 2 22 20 12 38 -6 22 -22z" />
                        <!--        <animateMotion dur="1s" repeatCount="indefinite" rotate="auto"></animateMotion>-->
                        <!--        </path>-->
                        <path d="M445 631 c-49 -30 -68 -58 -72 -108 -13 -151 176 -210 258 -81 39 64 10 154 -62 190 -44 23 -86 23 -124
          -1z m136 -50 c55 -56 25 -159 -51 -176 -43 -9 -99 21 -117 63 -43 103 88 192 168 113z" />
                    </g>
                </svg>
            </a>
            <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            <a asp-area="" asp-controller="Posters" asp-action="Posters">Events</a>
            <a asp-area="" asp-controller="Posters" asp-action="AddPosters">Add Posters</a>
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            @*<a href="#">About us</a>*@
        </div>
        <div class="links">
            @if (Accessor.HttpContext.Session.GetInt32("userId") != null)
            {
                <a asp-area="" asp-controller="Auth" asp-action="Logout">Log out</a>
            }
            else
            {
            <a asp-area="" asp-controller="Auth" asp-action="SignIn">Sign in</a>
            }
            <div class="lang" onclick="change_lang(this)"><span toggle>en</span>|<span>ua</span></div>
        </div>
    </nav>
    @RenderBody()
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        let options = document.getElementsByTagName("option");
        for (var i = 0; i < options.length; i++) {
            if (options[i].value != "") {
                options[i].innerHTML = options[i].value;
            }
        }
    </script>
    @if (TempData["Alert"] != null)
    {
        <script>
            alert("@Html.Raw(TempData["Alert"])");
        </script>
    }
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>